# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zipper.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 422)
        MainWindow.setStyleSheet("background-color: rgb(57, 57, 57);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 681, 401))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(340, 320, 331, 81))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_archive = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.button_archive.setMaximumSize(QtCore.QSize(120, 35))
        self.button_archive.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 255);\n"
"border-style:none;\n"
"border-radius: 10px;\n"
"font-size: 15px;\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(170, 85, 255);\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.button_archive.setObjectName("button_archive")
        self.horizontalLayout_3.addWidget(self.button_archive)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 681, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_zip = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edit_zip.setMaximumSize(QtCore.QSize(550, 25))
        self.edit_zip.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.edit_zip.setObjectName("edit_zip")
        self.horizontalLayout.addWidget(self.edit_zip)
        self.button_zip = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_zip.setMaximumSize(QtCore.QSize(120, 35))
        self.button_zip.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 255);\n"
"border-style:none;\n"
"border-radius: 10px;\n"
"font-size: 15px;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(170, 85, 255);\n"
"}\n"
"\n"
"")
        self.button_zip.setObjectName("button_zip")
        self.horizontalLayout.addWidget(self.button_zip)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 160, 681, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.edit_output = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.edit_output.setMaximumSize(QtCore.QSize(550, 25))
        self.edit_output.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.edit_output.setObjectName("edit_output")
        self.horizontalLayout_4.addWidget(self.edit_output)
        self.button_output = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.button_output.setMaximumSize(QtCore.QSize(120, 35))
        self.button_output.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 255);\n"
"border-style:none;\n"
"border-radius: 10px;\n"
"font-size: 15px;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: rgb(170, 85, 255);\n"
"}\n"
"\n"
"")
        self.button_output.setObjectName("button_output")
        self.horizontalLayout_4.addWidget(self.button_output)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 411, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.edit_filename = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_filename.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.edit_filename.setObjectName("edit_filename")
        self.horizontalLayout_2.addWidget(self.edit_filename)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 140, 111, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 87, 20))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(200, 220, 481, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Open Sans Semibold\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comp_methodbox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.comp_methodbox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comp_methodbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style:none;\n"
"border-radius:5px;\n"
"")
        self.comp_methodbox.setCurrentText("")
        self.comp_methodbox.setObjectName("comp_methodbox")
        self.horizontalLayout_5.addWidget(self.comp_methodbox)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(200, 270, 481, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Open Sans Semibold\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comp_levelbox = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.comp_levelbox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comp_levelbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style:none;\n"
"border-radius:5px;")
        self.comp_levelbox.setCurrentText("")
        self.comp_levelbox.setObjectName("comp_levelbox")
        self.horizontalLayout_6.addWidget(self.comp_levelbox)
        self.progbrar = QtWidgets.QProgressBar(self.frame)
        self.progbrar.setGeometry(QtCore.QRect(20, 320, 301, 23))
        self.progbrar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.progbrar.setProperty("value", 24)
        self.progbrar.setObjectName("progbrar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_archive.setText(_translate("MainWindow", "Archive"))
        self.edit_zip.setPlaceholderText(_translate("MainWindow", "Source Folder"))
        self.button_zip.setText(_translate("MainWindow", "Browse"))
        self.edit_output.setPlaceholderText(_translate("MainWindow", "Destination Folder"))
        self.button_output.setText(_translate("MainWindow", "Pick"))
        self.label_3.setText(_translate("MainWindow", "File Name"))
        self.edit_filename.setText(_translate("MainWindow", "MyZip"))
        self.edit_filename.setPlaceholderText(_translate("MainWindow", "File name"))
        self.label.setText(_translate("MainWindow", "Destination Path"))
        self.label_2.setText(_translate("MainWindow", "Source Path"))
        self.label_4.setText(_translate("MainWindow", "Compression Method: "))
        self.label_5.setText(_translate("MainWindow", "Compression Level: "))
